---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Dashboard"
subtitle: "Admin"
logo: "assets/icons/pwa-192x192.png"
icon: "fa-solid fa-mug-hot" # Optional icon
stylesheet:
  - "assets/custom.css"

# Other icon options
# "fa-solid fa-house-chimney"
# "fa-solid fa-server"
# "fa-solid fa-house-lock"
# "fa-solid fa-mug-hot"

header: true
#footer: false
footer: '<p><span class="has-text-danger">❗ Unauthorized access to this server is prohibited. Legal action will be taken. Disconnect now. ❗</span></p>' # Comment it out if you want to hide it.

theme: default
colors:
  light:
    highlight-primary: "#D7B99E"
    highlight-secondary: "#E5D5C9"
    highlight-hover: "#6B4F38"
    background: "#F2EFE6"
    card-background: "#F5F5F5"
    text: "#6B4F38"
    text-header: "#6B4F38"
    text-title: "#38220F"
    text-subtitle: "#6B6B6B"
    card-shadow: rgba(0, 0, 0, 0.2)
    link: "#3273dc"
    link-hover: "#ffdd57"
    #background-image: "/assets/resources/backgrounds/light-bg.png"
  dark:
    highlight-primary: "#1A120B"
    highlight-secondary: "#3C2A21"
    highlight-hover: "#AD8B73"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#AD8B73"
    text-header: "#AD8B73"
    text-title: "#E3CAA5"
    text-subtitle: "#afafaf"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc" # #6b717c
    link-hover: "#ffdd57"
    #background-image: "/assets/resources/backgrounds/dark-bg.png"
    
message:
    style: "is-dark is-small"
    title: "Lofi Radio  (M to unmute)"
    icon: "fa-brands fa-youtube"
    content: '<iframe width="100%" height="250" align="center" src="https://www.youtube.com/embed/jfKfPfyJRdk?controls=1&rel=0&autoplay=1&mute=1" title="lofi hip hop radio - beats to relax/study to" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>'
    
# Services
services:
  - name: "Server"
    icon: "fas fa-server"
    items:
      - name: "Portainer 🐳"
        logo: "assets/resources/logos/portainer.svg"
        subtitle: "Manage docker containers"
        tag: "server"
        keywords: "portainer"
        url: "http://192.168.1.100:9999/#!/auth"
        type: "Portainer"
        apikey: "ptr_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
        environments:
         - "local"
        target: "_blank"
      - name: "Dozzle 📒"
        logo: "assets/resources/logos/dozzle.svg"
        subtitle: "View Docker logs live"
        tag: "server"
        keywords: "dozzle"
        url: "http://192.168.1.100:10002/"
        target: "_blank"
      - name: "Netdata 💹"
        logo: "assets/resources/logos/netdata.svg"
        subtitle: "Monitor your server"
        tag: "server"
        keywords: "netdata"
        url: "http://192.168.1.100:19999"
        target: "_blank"
  - name: "Media"
    icon: "fas fa-video"
    items:
      - name: "Jellyfin 🎥"
        logo: "assets/resources/logos/jellyfin.svg"
        #subtitle: "Watch movies and shows"
        tag: "media"
        keywords: "jellyfin"
        url: "http://192.168.1.100:8096"
        type: "Emby"
        apikey: "<---insert-api-key-here--->"
        libraryType: "movies" #Choose which stats to show. Can be one of: music, series or movies.
        target: "_blank"
      - name: "Jellyseerr 📝"
        logo: "assets/resources/logos/jellyseerr.svg"
        subtitle: "Managing requests for your media library"
        tag: "media"
        keywords: "jellyseerr"
        url: "http://192.168.1.100:8097/"
        target: "_blank"
      - name: "Stash 📦"
        logo: "assets/resources/logos/stash.png"
        subtitle: "Stash away your media"
        tag: "media"
        keywords: "stash"
        url: "http://192.168.1.100:10005/"
        target: "_blank"
  - name: "Storage"
    icon: "fa-solid fa-folder-tree"
    items:
      - name: "Files 📂"
        logo: "assets/resources/logos/filebrowser.svg"
        subtitle: "Manage files"
        tag: "storage"
        keywords: "files"
        url: "http://192.168.1.100:10001/files/"
        target: "_blank"
      - name: "Scrutiny 💿"
        logo: "assets/resources/logos/scrutiny-white.svg" # or scrutiny-black.svg
        subtitle: "Monitor drives SMART status"
        tag: "storage"
        keywords: "scrutiny"
        url: "http://192.168.1.100:10003/web/dashboard"
        target: "_blank"
      - name: "Doku 🔵️"
        icon: "fa-solid fa-hard-drive"
        #logo: "assets/resources/logos/doku.svg"
        subtitle: "Docker disk usage dashboard"
        tag: "storage"
        keywords: "doku"
        url: "http://192.168.1.100:10004"
        target: "_blank"
  - name: "Network"
    icon: "fa-solid fa-network-wired"
    items:
      - name: "Pi-Hole 🕳️"
        logo: "assets/resources/logos/pihole.svg"
        #subtitle: "DNS Sinkhole for home network"
        tag: "network"
        keywords: "pihole"
        url: "http://192.168.1.100:10008/admin"
        type: "PiHole"
        apikey: "<---insert-api-key-here--->" # optional, needed if web interface is password protected
        #background: black
        target: "_blank"
      - name: "WireGuard 🛡"
        logo: "assets/resources/logos/wireguard.svg"
        subtitle: "Secure VPN Tunnel"
        tag: "network"
        keywords: "wireguard"
        #type: "Ping"
        url: "http://192.168.1.100:51821" 
        #method: "head"
        target: "_blank"
      - name: "Pi.Alert ❗️"
        logo: "assets/resources/logos/pi.alert.png"
        subtitle: "A Intrusion Detection System"
        tag: "network"
        keywords: "pi.alert"
        type: "Ping"
        url: "http://192.168.1.100:10009"
        target: "_blank"
      - name: "Samba 🍽️"
        icon: "fa-solid fa-person-chalkboard"
        #logo: "assets/resources/logos/samba.svg"
        subtitle: "Network file sharing protocol"
        tag: "network"
        keywords: "samba"
        url: "http://192.168.1.100:10002/container/043fdb6c37fc"
        target: "_blank"
      - name: "Syncthing 🔁"
        logo: "assets/resources/logos/syncthing.svg"
        subtitle: "Network Directory Sync"
        tag: "network"
        keywords: "syncthing"
        url: "http://192.168.1.100:8384"
        target: "_blank"
  - name: "Services"
    icon: "fa-solid fa-ice-cream"
    items:
      - name: "Gitea 🌱"
        logo: "assets/resources/logos/gitea.svg"
        subtitle: "Local version control"
        tag: "services"
        keywords: "gitea"
        url: "http://192.168.1.100:10010/"
        target: "_blank"
      - name: "Duplicacy 🔰"
        logo: "assets/resources/logos/duplicacy.png"
        subtitle: "Backup your stuff"
        tag: "services"
        keywords: "duplicacy"
        url: "http://192.168.1.100:10014"
        target: "_blank"
      - name: "IT-Tools 🔧"
        logo: "assets/resources/logos/it-tools.svg"
        subtitle: "Useful tools for developers"
        tag: "services"
        keywords: "it-tools"
        url: "http://192.168.1.100:10011/"
        target: "_blank"
      #- name: "Watchtower 🔦"
      #  logo: "assets/resources/logos/watchtower.svg"
      #  subtitle: "Automating Docker container updates"
      #  tag: "services"
      #  keywords: "watchtower"
      #  url: "http://192.168.1.100:10002/container/30e289c792b6"
      #  target: "_blank"
      - name: "QDirStat 🧱"
        logo: "assets/resources/logos/qdirstat.svg"
        subtitle: "Show where your disk space has gone"
        tag: "services"
        keywords: "qdirstat"
        url: "http://192.168.1.100:10012/"
        target: "_blank"
  - name: "Downloaders"
    icon: "fa-solid fa-download"
    items:
      - name: "Aria2 Pro 🚀"
        logo: "assets/resources/logos/ariang.png"
        subtitle: "Manage general downloads"
        tag: "downloaders"
        keywords: "aria2-pro"
        url: "http://192.168.1.100:10007/#!/settings/rpc/set/http/192.168.1.100/6800/jsonrpc/Y2hhbmdlbWU=" # RPC Token in base64 = Y2hhbmdlbWU=
        target: "_blank"
      - name: "qBittorrent 🌐"
        logo: "assets/resources/logos/qbittorrent.svg"
        subtitle: "Manage torrents"
        tag: "downloaders"
        keywords: "qbittorrent"
        url: "http://192.168.1.100:10006/#/"
        target: "_blank"
      - name: "Tube Archivist 📼"
        logo: "assets/resources/logos/tube-archivist-dark.png"
        subtitle: "YouTube media server"
        tag: "downloaders"
        keywords: "tube-archivist"
        url: "http://192.168.1.100:10013/#/"
        target: "_blank"
