version: '3.3'
services:
    dashdot:
        container_name: dashdot
        image: mauricenino/dashdot
        ports:
            - '9683:3001'
        environment:
            - DASHDOT_ACCEPT_OOKLA_EULA=true
            - DASHDOT_ENABLE_CPU_TEMPS=true
            - DASHDOT_SHOW_HOST=true
            - DASHDOT_SHOW_DASH_VERSION=icon_hover
            - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
            - DASHDOT_PAGE_TITLE=server
        volumes:
            - '/etc/os-release:/etc/os-release:ro'
            - '/proc/1/ns/net:/mnt/host_ns_net:ro'
            - '/:/mnt/host:ro'
        privileged: false
