version: "3"
services:
  pialert:
    container_name: pi-alert
    image: "jokobsk/pi.alert:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /srv/stacks/pi.alert/config:/home/pi/pialert/config
      - pi.alert_db:/home/pi/pialert/db

      # (optional) useful for debugging if you have issues setting up the container
      #- /srv/stacks/pi.alert/logs:/home/pi/pialert/front/log
    environment:
      - TZ=America/New_York    
      - HOST_USER_ID=1000
      - HOST_USER_GID=1000
      - PORT=10009
      # - SCAN_SUBNETS="['192.168.1.0/24 --interface=eth0']" # set this in the webui
volumes:
  pi.alert_db:

# Archived