version: "3.8"
services:
  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    restart: no
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=changeme #use this to authentication, # RPC Token in base64 = Y2hhbmdlbWU=
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      #- CUSTOM_TRACKER_URL=
      - TZ=America/New_York
    volumes:
      - /srv/stacks/aria2-pro/config:/config
      - /srv/stacks/aria2-pro/downloads:/downloads
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
#    network_mode: host
    network_mode: bridge
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m

# AriaNg is just a static web page, usually you only need to deploy on a single host.
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    restart: no
    command: --port 10007 --ipv6
#    network_mode: host
    network_mode: bridge
    ports:
      - 10007:10007
    logging:
      driver: json-file
      options:
        max-size: 1m
