version: '3.3'
services:
    doku:
        container_name: doku
        image: amerkurev/doku
        restart: unless-stopped
        ports:
            - '10004:10004'
        environment:
            - PORT=10004
            - SCAN_INTENSITY=light
            - SCAN_BINDMOUNTS_INTERVAL=43200 # Scan every 12hrs
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '/:/hostroot:ro'
