version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    ports:
      - 10002:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_USERNAME=admin
      - DOZZLE_PASSWORD=changeme
    restart: always