version: "3"
services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.20.4
    restart: always
    ports:
      - "10010:10010"
      - "2222:22"
    volumes:
      - /srv/stacks/gitea/data:/data
      - /srv/stacks/gitea/lfs:/lfs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - APP_NAME=Gitea
      - GITEA__ui__DEFAULT_THEME=arc-green
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__HOST=192.168.1.100:10010
      - GITEA__server__ROOT_URL=http://192.168.1.100:10010/
      - GITEA__server__HTTP_PORT=10010
      - GITEA__server__SSH_DOMAIN=192.168.1.100
      - GITEA__server__DOMAIN=192.168.1.100
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__server__LFS_START_SERVER=true
      - GITEA__lfs__PATH=/lfs
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      - GITEA__service__NO_REPLY_ADDRESS=noreply-gitea.192.168.1.100
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=true
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__DISABLE_REGISTER_EMAIL_CONFIRM=false
      - GITEA__service__DISABLE_ALLOW_ONLY_EXTERNAL_REGISTRATION=false
      - GITEA__mailer__ENABLED=false
    security_opt:
      - no-new-privileges:true