services:
  gitea:
    container_name: gitea
    image: docker.gitea.com/gitea:1.27.3
    restart: always
    ports:
      - "10010:3000"
      - "2222:22" # change right to port 2222 paired with commenting in ssh section in env
    volumes:
      - /srv/stacks/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # Added
      - APP_NAME=Tea
      # Enable this to migrate from old container that are already running
      - GITEA__migrations__ALLOW_LOCALNETWORKS=true
      # SMTP
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__PROTOCOL=smtp
      - GITEA__mailer__SMTP_ADDR=192.168.1.200
      - GITEA__mailer__SMTP_PORT=1025
      - GITEA__mailer__FROM=gitea@server.home.arpa
      - GITEA__mailer__USER=Gitea
      - GITEA__mailer__PASSWD=none
      # Mail
      - GITEA__service__ENABLE_NOTIFY_MAIL=true
      - GITEA__service__REGISTER_EMAIL_CONFIRM=false
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=false
      - GITEA__service__NO_REPLY_ADDRESS=noreply.gitea.server.home.arpa
      # openid
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      # server
      - GITEA__server__OFFLINE_MODE=true
      - GITEA__server__LFS_START_SERVER=true
      # ssh
      #- GITEA__server__START_SSH_SERVER=true
      #- GITEA__server__SSH_LISTEN_PORT=2222
      #- GITEA__server__SSH_PORT=2222