version: "3.8"

services:
  hoodik:
    image: hudik/hoodik:latest
    container_name: hoodik
    ports:
      - "5443:5443"
    environment:
      DATA_DIR: /data
      APP_URL: "https://192.168.1.200:5443"
      # Email Settings
      MAILER_TYPE: smtp # Default: none
      SMTP_ADDRESS: 192.168.1.200
      SMTP_PORT: 1025
      SMTP_TLS_MODE: none
      SMTP_USERNAME: "Hoodik"
      SMTP_PASSWORD: "none"
      SMTP_DEFAULT_FROM_EMAIL: "hoodik@server.home.arpa"
    volumes:
      - /srv/stacks/hoodik/data:/data
    restart: unless-stopped
