services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
      - "1010:1110" # POP3
    environment:
      - MP_MAX_MESSAGES=500
      - MP_DATABASE=/data/mailpit.db
      - TZ=America/New_York
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
      - MP_POP3_AUTH=admin:changeme
      - MP_UI_AUTH=admin:changeme
      - MP_TAGS_TITLE_CASE=true
      - MP_TAGS_USERNAME=true
      - MP_TAGS_CONFIG=/data/tags.yaml
    volumes:
      - /srv/stacks/mailpit/data:/data
