version: "3.7"
services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    restart: always
    ports:
      - "10012:10012"
    volumes:
      - /srv/stacks/qbittorrent/config:/config
      - /srv/stacks/qbittorrent/downloads:/downloads # Has to be changed to be default directory in web-ui
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - WEBUI_PORTS=10012/tcp
      - TZ=America/New_York
      - LIBTORRENT=v1

# Username: admin
# Password: Temporary password in logs, set in web-ui
