version: '3.4'
services:
  stash:
    container_name: stash
    image: stashapp/stash:latest
    restart: unless-stopped
    ports:
      - "10005:10005"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=10005
    volumes:
      - /etc/localtime:/etc/localtime:ro
      
      ## Keep configs, scrapers, and plugins here.
      -  /srv/stacks/stash/config:/root/.stash
      ## Point this at your collection.
      - /srv/stacks/stash/data:/data:ro
      ## This is where your stash's metadata lives
      - /srv/stacks/stash/metadata:/metadata
      ## Any other cache content.
      - /srv/stacks/stash/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - /srv/stacks/stash/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /srv/stacks/stash/generated:/generated