version: "3.8"
services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy
    restart: unless-stopped
    ports:
      - "51820:51820/udp" # Port forward this
      - "51821:51821/tcp" # Web-ui Port
    environment:
      - WG_HOST=XXX.XXX.XXX.XXX # Set this to your public ip address
      - PASSWORD=changeme # Web-ui Password
      - WG_DEFAULT_DNS=192.168.1.1, 1.1.1.1 # You may want to set this to pi-hole's dns
      - WG_ALLOWED_IPS=192.168.1.100/32 # https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS= 10.8.0.x
      # - WG_MTU=1420
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
    volumes:
      - /srv/stacks/wg-easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1